const fs = require('fs/promises');
const path = require('path');
const { spawn } = require('child_process');
const packageConfig = require('../package.json');

const packageRoot = path.resolve(__dirname, '..');
const requiredComponentsDir = path.join(packageRoot, 'required-components');
const distDir = path.join(packageRoot, 'dist');
const distRequiredComponentsDir = path.join(distDir, 'required-components');
const stateBannerDir = path.join(requiredComponentsDir, 'state-banner');
const stateBannerSource = path.join(stateBannerDir, 'styles.scss');
const stateBannerOutput = path.join(stateBannerDir, 'styles.css');
const cdnOrigin = 'https://unpkg.com';
const localPackageRoutePattern = /\/(@massds\/mds-[a-z0-9-]+)\/([^"'<>\s)]+)/g;
const dependencyVersionCache = new Map();
const generatedCssBanner =
  '/* This file is generated by components/scripts/build.js. Edit styles.scss instead. */';

function getSassBin() {
  const sassEntry = require.resolve('sass', {
    paths: [packageRoot]
  });

  return path.join(path.dirname(sassEntry), 'sass.js');
}

function compileSass(inputFile, outputFile) {
  return new Promise((resolve, reject) => {
    const sassBin = getSassBin();
    const child = spawn(
      process.execPath,
      [sassBin, '--no-source-map', '--style=expanded', inputFile, outputFile],
      {
        cwd: packageRoot,
        stdio: 'inherit'
      }
    );

    child.on('exit', (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`Sass compilation failed for ${path.basename(inputFile)} with exit code ${code}`));
    });

    child.on('error', reject);
  });
}

async function cleanDist() {
  await fs.rm(distDir, { recursive: true, force: true });
}

function normalizeDependencyVersion(packageName, rawVersion) {
  const normalizedVersion = rawVersion.trim().replace(/^workspace:/, '');
  const versionMatch = normalizedVersion.match(
    /^[~^=v]*(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)$/
  );

  if (!versionMatch) {
    throw new Error(
      `${packageName} must use an exact, caret, or tilde semver in devDependencies to build CDN URLs. Received: ${rawVersion}`
    );
  }

  return versionMatch[1];
}

function getDependencyVersion(packageName) {
  if (dependencyVersionCache.has(packageName)) {
    return dependencyVersionCache.get(packageName);
  }

  const rawVersion = packageConfig.devDependencies?.[packageName];

  if (!rawVersion) {
    throw new Error(`${packageName} is referenced in component HTML but is missing from devDependencies.`);
  }

  const version = normalizeDependencyVersion(packageName, rawVersion);
  dependencyVersionCache.set(packageName, version);

  return version;
}

function toCdnUrl(packageName, assetPath) {
  return `${cdnOrigin}/${packageName}@${getDependencyVersion(packageName)}/${assetPath}`;
}

function replaceLocalPackageRoutes(html) {
  return html.replace(localPackageRoutePattern, (_match, packageName, assetPath) =>
    toCdnUrl(packageName, assetPath)
  );
}

async function getHtmlFiles(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const entryPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        return getHtmlFiles(entryPath);
      }

      return entry.isFile() && path.extname(entry.name) === '.html' ? [entryPath] : [];
    })
  );

  return files.flat();
}

async function rewriteHtmlCdnReferences(dir) {
  const htmlFiles = await getHtmlFiles(dir);

  await Promise.all(
    htmlFiles.map(async (htmlFile) => {
      const html = await fs.readFile(htmlFile, 'utf8');
      const rewrittenHtml = replaceLocalPackageRoutes(html);

      if (rewrittenHtml !== html) {
        await fs.writeFile(htmlFile, rewrittenHtml, 'utf8');
      }
    })
  );
}

function shouldCopyRequiredComponent(sourcePath) {
  return path.basename(sourcePath) !== '.DS_Store';
}

async function build() {
  await cleanDist();
  await compileSass(stateBannerSource, stateBannerOutput);

  const compiledCss = await fs.readFile(stateBannerOutput, 'utf8');
  await fs.writeFile(
    stateBannerOutput,
    `${generatedCssBanner}\n${compiledCss}`,
    'utf8'
  );
  await fs.cp(requiredComponentsDir, distRequiredComponentsDir, {
    filter: shouldCopyRequiredComponent,
    recursive: true
  });
  await rewriteHtmlCdnReferences(distRequiredComponentsDir);
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
