const fs = require('fs/promises');
const path = require('path');
const { spawn } = require('child_process');

const packageRoot = path.resolve(__dirname, '..');
const stateBannerDir = path.join(packageRoot, 'required-components', 'state-banner');
const stateBannerSource = path.join(stateBannerDir, 'styles.scss');
const stateBannerOutput = path.join(stateBannerDir, 'styles.css');

function getSassBin() {
  const sassEntry = require.resolve('sass', {
    paths: [packageRoot]
  });

  return path.join(path.dirname(sassEntry), 'sass.js');
}

function compileSass(inputFile, outputFile) {
  return new Promise((resolve, reject) => {
    const sassBin = getSassBin();
    const child = spawn(
      process.execPath,
      [sassBin, '--pkg-importer=node', '--no-source-map', '--style=expanded', inputFile, outputFile],
      {
        cwd: packageRoot,
        stdio: 'inherit'
      }
    );

    child.on('exit', (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(`Sass compilation failed for ${path.basename(inputFile)} with exit code ${code}`));
    });

    child.on('error', reject);
  });
}

async function build() {
  await compileSass(stateBannerSource, stateBannerOutput);

  const compiledCss = await fs.readFile(stateBannerOutput, 'utf8');
  await fs.writeFile(
    stateBannerOutput,
    `/* This file is generated by components/scripts/build.js. Edit styles.scss instead. */\n${compiledCss}`,
    'utf8'
  );
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
